module.exports.userErrorCode = {
    emailAlreadyExists: {
        codeError: 'emailAlreadyExists',
        msg: 'Email already exists!'
    },
    validationError: {
        codeError: 'validationError',
        msg: 'Error in validation',
        inputs: []
    },
    userNotFound: {
        codeError: 'userNotFound',
        msg: 'User not found'
    },
    userNotUpdated: {
        codeError: 'userNotUpdated',
        msg: 'User not updated'
    }
}